// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using pdfProcessor.Data.DbContexts;

#nullable disable

namespace pdfProcessor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903105518_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("pdfProcessor.Features.DocumentProcess.DocumentProcessDto", b =>
                {
                    b.Property<Guid>("DocumentProcessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("DocumentProcessId");

                    b.Property<DateTime>("CompletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CompletedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("DocumentId");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("ErrorMessage");

                    b.Property<string>("JobStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("JobStatus");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StartedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("DocumentProcessId")
                        .HasName("DocumentProcessId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("DocumentProcessId");

                    b.ToTable("DocumentProcess", (string)null);
                });

            modelBuilder.Entity("pdfProcessor.Features.DocumentUpload.DocumentDto", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("DocumentId");

                    b.Property<string>("FileName")
                        .HasColumnType("text")
                        .HasColumnName("FileName");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("FileSize");

                    b.Property<string>("MimeType")
                        .HasColumnType("text")
                        .HasColumnName("MimeType");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UploadedAt")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("DocumentId");

                    b.HasIndex("DocumentId")
                        .IsUnique();

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("pdfProcessor.Features.DocumentProcess.DocumentProcessDto", b =>
                {
                    b.HasOne("pdfProcessor.Features.DocumentUpload.DocumentDto", "Document")
                        .WithMany("DocumentJobs")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("pdfProcessor.Features.DocumentUpload.DocumentDto", b =>
                {
                    b.Navigation("DocumentJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
